"""OxeePhone: recordings generated by the voice model, audio greetings."""

from types import SimpleNamespace

import pytest

from api.brand import recordings

GRAPH = {
    "nodes": [
        {"id": "1", "type": "startCall", "data": {"greeting_type": "text", "greeting": "Bonjour !"}},
        {"id": "2", "type": "agentNode", "data": {}},
    ],
    "edges": [],
}


def test_audio_greeting_keeps_the_text():
    graph = recordings.with_audio_greeting(GRAPH, 42)
    data = graph["nodes"][0]["data"]
    assert data == {"greeting_type": "audio", "greeting": "Bonjour !", "greeting_recording_id": "42"}
    assert GRAPH["nodes"][0]["data"]["greeting_type"] == "text"  # not mutated
    back = recordings.with_audio_greeting(graph, None)["nodes"][0]["data"]
    assert back["greeting_type"] == "text" and back["greeting"] == "Bonjour !"
    with pytest.raises(recordings.RecordingError):
        recordings.with_audio_greeting({"nodes": []}, 1)


@pytest.fixture
def fake_backend(monkeypatch):
    from api.brand import local_models
    from api.db import db_client
    from api.services import storage

    store, created, synth = {}, [], {}
    tts = SimpleNamespace(
        base_url="http://tts/v1", model="voxee-tts-pro", voice="fr_cedric", speed=1.0,
        language="fr", volume_gain_db=0.0, pronunciations=None, provider="speaches",
        get_all_api_keys=lambda: ["k"],
    )

    async def organization_tts(org):
        return tts

    async def synthesize_preview(**kwargs):
        synth.update(kwargs)
        return b"RIFF" + b"\x00" * 40

    async def exists(rid, org):
        return rid == "taken"

    async def create_recording(**kwargs):
        created.append(kwargs)
        return SimpleNamespace(id=7, **{k: kwargs[k] for k in ("recording_id", "storage_key")})

    class _FS:
        async def acreate_file_from_bytes(self, key, data):
            store[key] = data
            return True

    monkeypatch.setattr(recordings, "organization_tts", organization_tts)
    monkeypatch.setattr(local_models, "synthesize_preview", synthesize_preview)
    monkeypatch.setattr(db_client, "check_recording_id_exists", exists)
    monkeypatch.setattr(db_client, "create_recording", create_recording)
    monkeypatch.setattr(storage, "storage_fs", _FS())
    return SimpleNamespace(store=store, created=created, synth=synth)


@pytest.mark.asyncio
async def test_generate_stores_a_recording(fake_backend):
    user = SimpleNamespace(id=3)
    rec = await recordings.generate(5, user, text="  Bonjour, vous êtes bien chez SNG.  ", voice="fr_lea", speed=1.1, name="accueil_sng")
    assert rec.recording_id == "accueil_sng"
    assert fake_backend.synth["voice"] == "fr_lea" and fake_backend.synth["speed"] == 1.1
    assert fake_backend.synth["max_chars"] == recordings.GENERATE_MAX_CHARS
    assert list(fake_backend.store) == ["recordings/5/accueil_sng/accueil_sng.wav"]
    row = fake_backend.created[0]
    assert row["transcript"] == "Bonjour, vous êtes bien chez SNG." and row["tts_voice_id"] == "fr_lea"
    assert row["metadata"]["generated"] is True and row["created_by"] == 3

    # Organization voice when none is chosen; generated name.
    rec = await recordings.generate(5, user, text="Au revoir.")
    assert fake_backend.synth["voice"] == "fr_cedric" and len(rec.recording_id) == 8

    for bad in ({"text": " "}, {"text": "x", "name": "taken"}, {"text": "x", "name": "a b"}, {"text": "x" * 1001}):
        with pytest.raises(recordings.RecordingError):
            await recordings.generate(5, user, **bad)
