"""Recordings generated by the organization's voice model, and greetings
played from a recording.

A generated recording is an ordinary organization recording (Recordings
screen, ``@`` in prompts, audio greetings): the text is synthesized with the
chosen voice and speed, stored as WAV and transcribed by its own text.
Using it as an agent's greeting switches the start node to an audio greeting
in a draft (the published version is untouched). The greeting text stays in
the node, so going back to a spoken text greeting is one switch away.
"""

from __future__ import annotations

import copy
import re
from typing import Any

from loguru import logger

from api.db import db_client

GENERATE_MAX_CHARS = 1000
START_NODE = "startCall"
NAME_RE = re.compile(r"^[a-zA-Z0-9_-]+$")


class RecordingError(Exception):
    pass


async def organization_tts(organization_id: int) -> Any:
    """The organization's voice model settings (Models › Voice)."""
    from api.services.configuration.ai_model_configuration import (
        get_organization_ai_model_configuration_v2,
    )

    stored = await get_organization_ai_model_configuration_v2(organization_id)
    pipeline = getattr(getattr(stored, "byok", None), "pipeline", None)
    tts = getattr(pipeline, "tts", None) if pipeline else None
    if tts is None or not getattr(tts, "base_url", None):
        raise RecordingError("No voice model configured (Models › Voice).")
    return tts


def _api_key(tts: Any) -> str | None:
    keys = tts.get_all_api_keys() if hasattr(tts, "get_all_api_keys") else []
    return keys[0] if keys else None


async def _unique_name(organization_id: int, wanted: str | None) -> str:
    from api.db.workflow_recording_client import generate_short_id

    if wanted:
        if not NAME_RE.match(wanted):
            raise RecordingError(
                "The name may only hold letters, digits, - and _."
            )
        if await db_client.check_recording_id_exists(wanted, organization_id):
            raise RecordingError(f"A recording named “{wanted}” already exists.")
        return wanted
    for _ in range(10):
        rid = generate_short_id(8)
        if not await db_client.check_recording_id_exists(rid, organization_id):
            return rid
    raise RecordingError("Could not pick a recording name.")


async def generate(
    organization_id: int,
    user: Any,
    *,
    text: str,
    voice: str | None = None,
    speed: float | None = None,
    name: str | None = None,
) -> Any:
    """Synthesize ``text`` and store it as an organization recording."""
    from api.brand.local_models import LocalModelsError, synthesize_preview
    from api.enums import StorageBackend
    from api.services.storage import storage_fs

    text = (text or "").strip()
    if not text:
        raise RecordingError("Write the text to speak.")
    if len(text) > GENERATE_MAX_CHARS:
        raise RecordingError(f"The text is limited to {GENERATE_MAX_CHARS} characters.")
    tts = await organization_tts(organization_id)
    voice = (voice or "").strip() or tts.voice
    speed = speed or getattr(tts, "speed", None)
    try:
        audio = await synthesize_preview(
            base_url=tts.base_url,
            api_key=_api_key(tts),
            model=tts.model,
            voice=voice,
            speed=speed,
            language=getattr(tts, "language", None),
            text=text,
            volume_gain_db=getattr(tts, "volume_gain_db", None),
            pronunciations=getattr(tts, "pronunciations", None),
            max_chars=GENERATE_MAX_CHARS,
        )
    except LocalModelsError as e:
        raise RecordingError(str(e)) from e

    recording_id = await _unique_name(organization_id, (name or "").strip() or None)
    storage_key = f"recordings/{organization_id}/{recording_id}/{recording_id}.wav"
    if not await storage_fs.acreate_file_from_bytes(storage_key, audio):
        raise RecordingError("The audio file could not be stored.")
    recording = await db_client.create_recording(
        recording_id=recording_id,
        organization_id=organization_id,
        transcript=text,
        storage_key=storage_key,
        storage_backend=StorageBackend.get_current_backend().value,
        created_by=user.id,
        tts_provider=str(getattr(tts, "provider", "") or "") or None,
        tts_model=tts.model,
        tts_voice_id=voice,
        metadata={
            "original_filename": f"{recording_id}.wav",
            "file_size_bytes": len(audio),
            "mime_type": "audio/wav",
            "language": getattr(tts, "language", None),
            "generated": True,
            "voice": voice,
            "speed": speed,
        },
    )
    logger.info(
        f"Generated recording {recording_id} ({len(text)} chars, voice {voice}) "
        f"for org {organization_id}"
    )
    return recording


def start_node(workflow_json: dict) -> dict | None:
    for node in (workflow_json or {}).get("nodes") or []:
        if node.get("type") == START_NODE:
            return node
    return None


async def _editable_version(organization_id: int, workflow_id: int):
    """The draft if there is one, else the published version."""
    from api.brand import db as brand_db

    workflow = await db_client.get_workflow(workflow_id, organization_id=organization_id)
    if workflow is None:
        raise LookupError("agent not found")
    draft = await db_client.get_draft_version(workflow_id)
    if draft is not None:
        return workflow, draft
    published = (
        await brand_db.get_workflow_version(workflow_id, workflow.released_definition_id)
        if workflow.released_definition_id
        else None
    )
    if published is None:
        raise RecordingError("The agent has no version to start from.")
    return workflow, published


async def agent_greeting(organization_id: int, workflow_id: int) -> dict:
    """What the agent says first (to prefill a recording)."""
    _, version = await _editable_version(organization_id, workflow_id)
    node = start_node(version.workflow_json or {})
    data = (node or {}).get("data") or {}
    override = (version.workflow_configurations or {}).get("voice_override") or {}
    return {
        "text": data.get("greeting") or "",
        "greeting_type": data.get("greeting_type") or "text",
        "greeting_recording_id": data.get("greeting_recording_id"),
        "voice": override.get("voice"),
        "speed": override.get("speed"),
    }


def with_audio_greeting(workflow_json: dict, recording_pk: int | None) -> dict:
    """The graph with its start node greeting from a recording (None: back
    to the text greeting)."""
    graph = copy.deepcopy(workflow_json or {})
    node = start_node(graph)
    if node is None:
        raise RecordingError("The agent has no start node.")
    data = node.setdefault("data", {})
    if recording_pk is None:
        data["greeting_type"] = "text"
    else:
        data["greeting_type"] = "audio"
        data["greeting_recording_id"] = str(recording_pk)
    return graph


async def set_greeting(
    organization_id: int, user: Any, workflow_id: int, recording_pk: int | None
) -> Any:
    """Save a draft whose greeting plays the recording (or the text again)."""
    from api.brand import versions

    label = None
    if recording_pk is not None:
        recording = await db_client.get_recording_by_id(recording_pk, organization_id)
        if recording is None:
            raise LookupError("recording not found")
        label = recording.recording_id
    _, base = await _editable_version(organization_id, workflow_id)
    graph = with_audio_greeting(base.workflow_json or {}, recording_pk)
    saved = await db_client.save_workflow_draft(
        workflow_id,
        workflow_definition=graph,
        workflow_configurations=base.workflow_configurations or {},
    )
    await versions.record_edit(
        saved,
        user,
        organization_id=organization_id,
        note=(f"Greeting: recording {label}" if label else "Greeting: text"),
    )
    return saved
