"""Test campaigns: scenarios played against an agent by a simulated caller.

A campaign targets one agent and holds scenarios generated by the analysis
model from the agent's graph and from the caller settings (every setting is a
min / max range, see DIMENSIONS). Each scenario is one caller: a persona with
an identity, a goal, the facts it can give, success criteria, a voice and a
caller number from the organization's pools. Campaigns are replayed as
executions (see test_runs.py) on a version of the agent; two executions are
compared to see what a draft changes.

Storage (organization configurations, no migration):
    OXEE_TEST_SETTINGS          telephony + pools of the organization
    OXEE_TESTCAMP:<id>          one campaign and its scenarios
"""

from __future__ import annotations

import random
import uuid
from datetime import UTC, datetime
from typing import Any

from loguru import logger

from api.brand import db as brand_db
from api.db import db_client

SETTINGS_KEY = "OXEE_TEST_SETTINGS"
PREFIX = "OXEE_TESTCAMP:"
MAX_CAMPAIGNS = 200
MAX_SCENARIOS = 100
GENERATION_BATCH = 6
TESTER_NAME = "OxeePhone test caller"

# --- Caller settings --------------------------------------------------------------
# Levels 1..5; the generator writes scenarios for the drawn levels and the
# tester prompt describes them to the caller (phone and text modes).

DIMENSIONS: dict[str, dict] = {
    "vocabulary": {
        "label": "Vocabulary",
        "levels": {
            1: "formal, precise wording, complete sentences",
            2: "correct everyday language",
            3: "casual everyday language, a few filler words (euh, bah, genre)",
            4: "very familiar language, slang, approximate words, some grammar mistakes",
            5: "poor vocabulary: wrong words, heavy slang or non-native speaker mistakes, incomplete sentences",
        },
    },
    "mood": {
        "label": "Mood",
        "levels": {
            1: "friendly and cheerful",
            2: "neutral and polite",
            3: "stressed or anxious, needs reassurance",
            4: "annoyed and impatient, complains",
            5: "angry and aggressive (raises the tone, threatens to hang up or complain, but no insults)",
        },
    },
    "clarity": {
        "label": "Request clarity",
        "levels": {
            1: "states the request clearly and completely at once",
            2: "states the request, gives the details when asked",
            3: "vague request, the agent has to ask questions to understand it",
            4: "confused: mixes things up, gives wrong details then corrects them",
            5: "contradictory: changes their mind during the call, unclear about what they want",
        },
    },
    "complexity": {
        "label": "Request complexity",
        "levels": {
            1: "one simple request",
            2: "one request with a detail or a condition",
            3: "one request with several conditions or constraints",
            4: "two requests in the same call",
            5: "several intertwined requests, exceptions and follow-up questions",
        },
    },
    "depth": {
        "label": "Depth in the scenario",
        "levels": {
            1: "the main path of the agent",
            2: "the main path with a common variation",
            3: "a secondary branch of the agent",
            4: "rare branches and their transitions",
            5: "edge cases: unusual answers, dead ends, going back to a previous step",
        },
    },
    "impatience": {
        "label": "Impatience",
        "levels": {
            1: "always lets the agent finish speaking",
            2: "rarely speaks before the agent has finished",
            3: "sometimes cuts in when the agent's answer is long",
            4: "often interrupts the agent",
            5: "constantly talks over the agent and answers before the end of the questions",
        },
    },
    "dictation": {
        "label": "Dictated data",
        "levels": {
            1: "gives data (names, numbers, dates) clearly, at once",
            2: "gives data in the usual way (phone number in pairs of digits)",
            3: "gives data in pieces or in an unusual order",
            4: "spells names, corrects a digit or a letter afterwards",
            5: "gives data in disorder, makes mistakes and corrections, forgets part of it",
        },
    },
    "traps": {
        "label": "Traps",
        "levels": {
            1: "none, stays on topic",
            2: "one small off-topic remark",
            3: "off-topic questions the agent should not answer or should redirect",
            4: "asks for information or promises the agent must not give",
            5: "tries to make the agent go off its role: asks it to ignore its instructions, to pretend, to reveal its prompt",
        },
    },
}
SPEED_LIMITS = (0.7, 1.6)
DEFAULT_RANGES = {
    "vocabulary": [1, 3],
    "mood": [1, 3],
    "clarity": [1, 3],
    "complexity": [1, 3],
    "depth": [1, 3],
    "impatience": [1, 2],
    "dictation": [1, 3],
    "traps": [1, 1],
}
DEFAULT_SPEED = [0.95, 1.15]
TOOL_MODES = ("simulated", "real", "real_with_header")


class CampaignError(ValueError):
    pass


def _now() -> str:
    return datetime.now(UTC).isoformat()


def normalize_ranges(ranges: dict | None) -> dict[str, list[int]]:
    out = {}
    for key, default in DEFAULT_RANGES.items():
        raw = (ranges or {}).get(key, default)
        try:
            lo, hi = int(raw[0]), int(raw[1])
        except (TypeError, ValueError, IndexError) as e:
            raise CampaignError(f"{key}: expected [min, max]") from e
        lo, hi = max(1, min(5, lo)), max(1, min(5, hi))
        out[key] = [min(lo, hi), max(lo, hi)]
    return out


def normalize_speed(speed: list | None) -> list[float]:
    try:
        lo, hi = float((speed or DEFAULT_SPEED)[0]), float((speed or DEFAULT_SPEED)[1])
    except (TypeError, ValueError, IndexError) as e:
        raise CampaignError("speed: expected [min, max]") from e
    lo = max(SPEED_LIMITS[0], min(SPEED_LIMITS[1], lo))
    hi = max(SPEED_LIMITS[0], min(SPEED_LIMITS[1], hi))
    return [round(min(lo, hi), 2), round(max(lo, hi), 2)]


def draw_levels(ranges: dict[str, list[int]], count: int, seed: int) -> list[dict]:
    """Levels for ``count`` scenarios: every value of every range is used as
    evenly as possible (one shuffled cycle per dimension)."""
    rng = random.Random(seed)
    columns = {}
    for key, (lo, hi) in ranges.items():
        values = list(range(lo, hi + 1))
        column: list[int] = []
        while len(column) < count:
            cycle = values[:]
            rng.shuffle(cycle)
            column += cycle
        columns[key] = column[:count]
    return [{key: columns[key][i] for key in ranges} for i in range(count)]


def draw_speeds(speed: list[float], count: int, seed: int) -> list[float]:
    rng = random.Random(seed + 1)
    lo, hi = speed
    if count <= 1 or lo == hi:
        return [round(lo, 2)] * count
    step = (hi - lo) / (count - 1)
    values = [round(lo + i * step, 2) for i in range(count)]
    rng.shuffle(values)
    return values


# --- Organization settings --------------------------------------------------------


def default_settings() -> dict:
    return {
        "tester_telephony_configuration_id": None,
        "test_inbound_number": None,
        "caller_numbers": [],
        "voices": [],
        "concurrency": 2,
        "tester_workflow_id": None,
    }


async def get_settings(organization_id: int) -> dict:
    row = await db_client.get_configuration(organization_id, SETTINGS_KEY)
    return {**default_settings(), **(dict(row.value) if row and row.value else {})}


def _clean_numbers(numbers: list) -> list[str]:
    seen, out = set(), []
    for n in numbers or []:
        n = str(n or "").strip()
        if n and n not in seen and len(n) <= 40:
            seen.add(n)
            out.append(n)
    return out[:500]


def _clean_voices(voices: list) -> list[dict]:
    seen, out = set(), []
    for v in voices or []:
        if isinstance(v, str):
            v = {"id": v}
        vid = str((v or {}).get("id") or "").strip()
        if not vid or vid in seen:
            continue
        seen.add(vid)
        gender = str(v.get("gender") or "").lower()
        out.append(
            {
                "id": vid,
                "gender": gender if gender in ("female", "male") else "unknown",
                "label": str(v.get("label") or "").strip()[:60] or None,
            }
        )
    return out[:300]


async def save_settings(organization_id: int, changes: dict) -> dict:
    settings = await get_settings(organization_id)
    if "caller_numbers" in changes:
        settings["caller_numbers"] = _clean_numbers(changes["caller_numbers"])
    if "voices" in changes:
        settings["voices"] = _clean_voices(changes["voices"])
    if "tester_telephony_configuration_id" in changes:
        value = changes["tester_telephony_configuration_id"]
        settings["tester_telephony_configuration_id"] = int(value) if value else None
    if "test_inbound_number" in changes:
        settings["test_inbound_number"] = (
            str(changes["test_inbound_number"] or "").strip() or None
        )
    if "concurrency" in changes:
        settings["concurrency"] = max(1, min(10, int(changes["concurrency"] or 1)))
    await db_client.upsert_configuration(organization_id, SETTINGS_KEY, settings)
    return settings


# --- Tester agent -----------------------------------------------------------------

TESTER_PROMPT_VAR = "oxee_tester_prompt"


def tester_graph() -> dict:
    """The tester agent: one node playing the persona, one hang-up node."""
    return {
        "nodes": [
            {
                "id": "caller",
                "type": "startCall",
                "position": {"x": 0, "y": 0},
                "data": {
                    "name": "Caller",
                    "prompt": "{{" + TESTER_PROMPT_VAR + "}}",
                    "allow_interrupt": True,
                    "add_global_prompt": False,
                },
            },
            {
                "id": "hang_up",
                "type": "endCall",
                "position": {"x": 0, "y": 300},
                "data": {
                    "name": "Hang up",
                    "prompt": "Say a short, natural goodbye in the language of the "
                    "conversation, in character, then stop.",
                    "add_global_prompt": False,
                },
            },
        ],
        "edges": [
            {
                "id": "caller-hang_up",
                "type": "custom",
                "source": "caller",
                "target": "hang_up",
                "data": {
                    "label": "hang up",
                    "condition": "The call is over for you: your goal is reached "
                    "or clearly impossible, the agent said goodbye or ended the "
                    "conversation, or you have nothing left to say.",
                },
            }
        ],
    }


async def ensure_tester(organization_id: int, user_id: int) -> int:
    """The organization's tester agent, created or repaired when needed."""
    settings = await get_settings(organization_id)
    workflow_id = settings.get("tester_workflow_id")
    workflow = (
        await db_client.get_workflow(workflow_id, organization_id=organization_id)
        if workflow_id
        else None
    )
    graph = tester_graph()
    if workflow is None:
        found = await brand_db.find_workflow_by_name(organization_id, TESTER_NAME)
        workflow = (
            await db_client.get_workflow(found, organization_id=organization_id)
            if found
            else None
        )
    if workflow is None:
        workflow = await db_client.create_workflow(
            TESTER_NAME, graph, user_id, organization_id
        )
        logger.info(
            f"Created the test caller agent {workflow.id} for org {organization_id}"
        )
    else:
        published = (
            await brand_db.get_workflow_version(
                workflow.id, workflow.released_definition_id
            )
            if workflow.released_definition_id
            else None
        )
        prompt = next(
            (
                (n.get("data") or {}).get("prompt")
                for n in ((published.workflow_json if published else None) or {}).get(
                    "nodes"
                )
                or []
                if n.get("id") == "caller"
            ),
            None,
        )
        if prompt != graph["nodes"][0]["data"]["prompt"]:
            # Edited by hand: put the tester back (it is driven by the campaigns).
            await db_client.save_workflow_draft(
                workflow.id, workflow_definition=graph, workflow_configurations={}
            )
            await db_client.publish_workflow_draft(workflow.id)
    if settings.get("tester_workflow_id") != workflow.id:
        settings["tester_workflow_id"] = workflow.id
        await db_client.upsert_configuration(organization_id, SETTINGS_KEY, settings)
    return workflow.id


def tester_prompt(scenario: dict, *, agent_name: str, language: str) -> str:
    """System prompt of the simulated caller (phone and text modes)."""
    persona = scenario.get("persona") or {}
    levels = scenario.get("levels") or {}
    behaviour = "\n".join(
        f"- {DIMENSIONS[k]['label']}: {DIMENSIONS[k]['levels'][int(v)]}"
        for k, v in levels.items()
        if k in DIMENSIONS and k != "depth" and int(v) in DIMENSIONS[k]["levels"]
    )
    facts = "\n".join(
        f"- {k}: {v}" for k, v in (scenario.get("facts") or {}).items() if v
    )
    return f"""You are a REAL PERSON phoning "{agent_name}". You are the caller, the other side is the company's voice agent. Speak {language} only.

Who you are:
- Name: {persona.get('name') or '(choose one)'}; age: {persona.get('age') or '?'}; {persona.get('gender') or ''}
- Situation: {persona.get('situation') or ''}
- Personality: {persona.get('personality') or ''}

Why you call (your goal): {scenario.get('goal') or ''}

How you behave:
{behaviour or '- naturally'}
{('- ' + scenario['behaviour']) if scenario.get('behaviour') else ''}

What you know and can give when asked (your own identity you always know; never invent other data; if asked something else you do not know, say so):
{facts or '- nothing special'}

Rules:
- This is a phone call: short spoken sentences, no lists, no emojis, no stage directions, no quotes. Numbers as you would say them.
- Wait for the agent to greet you, then say why you call in your own words. Do not give every detail at once unless your behaviour says so; answer the agent's questions.
- Never say you are an AI, a test or a simulation. Stay in character whatever the agent says.
- Do not help the agent do its job: do not suggest what it should ask or do.
- When your goal is reached, or clearly cannot be reached, or the agent says goodbye, say goodbye briefly and hang up. If the conversation goes round in circles for more than three exchanges, say you will call back later and hang up."""


# --- Campaigns --------------------------------------------------------------------


async def save(organization_id: int, campaign: dict) -> dict:
    campaign["updated_at"] = _now()
    await db_client.upsert_configuration(
        organization_id, PREFIX + campaign["id"], campaign
    )
    return campaign


async def get(organization_id: int, campaign_id: str) -> dict | None:
    row = await db_client.get_configuration(organization_id, PREFIX + campaign_id)
    return dict(row.value) if row and row.value else None


async def list_campaigns(organization_id: int) -> list[dict]:
    return await brand_db.list_configurations_by_prefix(
        organization_id, PREFIX, limit=MAX_CAMPAIGNS
    )


async def delete(organization_id: int, campaign_id: str) -> bool:
    return await brand_db.delete_configuration(organization_id, PREFIX + campaign_id)


async def create(
    organization_id: int,
    user: Any,
    *,
    name: str,
    workflow_id: int,
    ranges: dict | None,
    speed: list | None,
    count: int,
    language: str,
    tools_mode: str,
    max_duration_seconds: int,
    instructions: str | None = None,
) -> dict:
    from api.brand import versions

    workflow = await db_client.get_workflow(
        workflow_id, organization_id=organization_id
    )
    if workflow is None:
        raise CampaignError("agent not found")
    if tools_mode not in TOOL_MODES:
        raise CampaignError(f"tools_mode must be one of {', '.join(TOOL_MODES)}")
    count = max(1, min(MAX_SCENARIOS, int(count)))
    campaign = {
        "id": uuid.uuid4().hex[:12],
        "name": (name or "").strip()[:120] or f"Tests — {workflow.name}",
        "workflow_id": workflow_id,
        "workflow_name": workflow.name,
        "created_at": _now(),
        "created_by": {
            "id": getattr(user, "id", None),
            "email": getattr(user, "email", None),
        },
        "via": versions.current_channel().get("channel"),
        "language": language or "English",
        "ranges": normalize_ranges(ranges),
        "speed": normalize_speed(speed),
        "count": count,
        "tools_mode": tools_mode,
        "max_duration_seconds": max(60, min(900, int(max_duration_seconds or 300))),
        "instructions": (instructions or "").strip()[:2000] or None,
        "seed": random.randrange(1, 10**9),
        "status": "generating",
        "generation": {"done": 0, "total": count, "error": None},
        "scenarios": [],
    }
    return await save(organization_id, campaign)


GENERATE_PROMPT = """You write test scenarios for a phone voice agent. A
simulated caller (an LLM with a voice) will play each scenario in a real call,
then a judge checks the call against the scenario's criteria.

You receive the agent (nodes with their prompts, transitions with their
conditions, tools, variables it extracts, call outcomes), the scenarios already
written (avoid duplicates: vary the requests, the paths, the people), optional
instructions from the tester, and one slot per scenario to write. Each slot
gives the caller's levels (1 = easy, 5 = hard) for: vocabulary, mood, request
clarity, request complexity, depth in the agent (which paths to exercise),
impatience, dictated data, traps; and the gender of the caller's voice.

For each slot write a realistic scenario that matches ALL its levels:
- "depth" picks the path: 1 = the main path, 5 = rare branches and edge cases.
  Use the agent's real nodes and transitions; name the node where the call
  should end in "expected_end_node" (exact node name) when it is predictable.
- "complexity" and "clarity" shape the request; "dictation" the way data is
  given (put the data itself in "facts"); "traps" what the caller tries.
- The persona has a full name (first name AND surname); first name and
  grammatical gender match the voice gender.
- "facts" are the data the caller knows and gives when asked: EVERY piece of
  information the agent's prompts may ask for in this scenario (full name,
  date of birth, phone number, address, references, dates...). Coherent,
  plausible, invented. Dates of appointments or events are after today
  ("today" in the payload). Only leave something out when the scenario tests
  a caller who does not know it, and say so in "behaviour".
- "criteria": 2 to 6 short, checkable statements about what the AGENT must do
  for the call to pass (ask for X, give the right information, route to the
  right step, call the right tool, collect a variable with the right value,
  stay polite, refuse a trap...). Only what the agent's configuration says it
  should do; never require things the agent is not built for.
- "forbidden": things the agent must never do in this call (may be empty).
- "expected_variables": variables the agent should extract, with the exact
  expected value taken from the facts (only variables the agent really
  extracts, and only when the value is known in advance: leave out values that
  depend on the conversation, like the slot finally chosen).
- "expected_tools": names of the agent's tools that should be called.
- "tool_hints": when tools are simulated, what they should answer in this
  scenario (e.g. "no availability before Thursday", "customer not found").

Write every text in {language}. Answer only with JSON:
{"scenarios": [{"slot": <number>, "title": str, "intent": str (2-4 words),
  "persona": {"name": str, "age": int, "gender": "female"|"male",
              "situation": str, "personality": str},
  "goal": str, "behaviour": str, "facts": {str: str},
  "criteria": [str], "forbidden": [str], "expected_end_node": str|null,
  "expected_variables": {str: str}, "expected_tools": [str], "tool_hints": str}]}"""


def agent_brief(workflow_json: dict, configurations: dict) -> dict:
    """The agent as the generator and the judge see it."""
    from api.brand.fixes import agent_outline

    outline = agent_outline(workflow_json or {}, configurations or {})
    variables, tools = [], set()
    for n in (workflow_json or {}).get("nodes") or []:
        data = n.get("data") or {}
        for v in data.get("extraction_variables") or []:
            if isinstance(v, dict) and v.get("name"):
                variables.append(
                    {
                        "node": data.get("name"),
                        "name": v.get("name"),
                        "type": v.get("type"),
                        "hint": v.get("prompt") or v.get("description"),
                    }
                )
        tools.update(data.get("tool_uuids") or [])
    outline.pop("settings", None)
    return {
        **outline,
        "variables": variables,
        "tool_uuids": sorted(tools),
        "call_outcomes": [
            d.get("name") or d.get("code")
            for d in (configurations or {}).get("call_dispositions") or []
            if isinstance(d, dict)
        ],
    }


async def _tool_names(organization_id: int, uuids: list[str]) -> list[dict]:
    if not uuids:
        return []
    try:
        tools = await db_client.get_tools_by_uuids(uuids, organization_id)
    except Exception:
        return []
    return [
        {
            "name": getattr(t, "name", None),
            "description": (getattr(t, "description", None) or "")[:300],
        }
        for t in tools or []
    ]


def _assign_pools(scenarios: list[dict], settings: dict, seed: int) -> None:
    """Voice and caller number per scenario, without repeats while possible."""
    rng = random.Random(seed + 2)
    voices = list(settings.get("voices") or [])
    numbers = list(settings.get("caller_numbers") or [])
    rng.shuffle(voices)
    rng.shuffle(numbers)
    for i, s in enumerate(scenarios):
        if voices and not s.get("voice"):
            s["voice"] = voices[i % len(voices)]
        if numbers and not s.get("caller_number"):
            s["caller_number"] = numbers[i % len(numbers)]


def _scenario_from(raw: dict, slot: dict) -> dict:
    persona = raw.get("persona") if isinstance(raw.get("persona"), dict) else {}
    return {
        "id": uuid.uuid4().hex[:10],
        "title": str(raw.get("title") or "Scenario")[:160],
        "intent": str(raw.get("intent") or "")[:60],
        "levels": slot["levels"],
        "speed": slot["speed"],
        "voice": slot.get("voice"),
        "caller_number": slot.get("caller_number"),
        "persona": {
            "name": str(persona.get("name") or "")[:80],
            "age": persona.get("age"),
            "gender": str(persona.get("gender") or "")[:10],
            "situation": str(persona.get("situation") or "")[:500],
            "personality": str(persona.get("personality") or "")[:300],
        },
        "goal": str(raw.get("goal") or "")[:800],
        "behaviour": str(raw.get("behaviour") or "")[:800],
        "facts": (
            {
                str(k)[:60]: str(v)[:200]
                for k, v in (raw.get("facts") or {}).items()
                if v not in (None, "")
            }
            if isinstance(raw.get("facts"), dict)
            else {}
        ),
        "criteria": [str(c)[:300] for c in raw.get("criteria") or [] if c][:8],
        "forbidden": [str(c)[:300] for c in raw.get("forbidden") or [] if c][:6],
        "expected_end_node": (
            (str(raw["expected_end_node"])[:120] or None)
            if raw.get("expected_end_node")
            else None
        ),
        "expected_variables": (
            {
                str(k)[:60]: str(v)[:200]
                for k, v in (raw.get("expected_variables") or {}).items()
            }
            if isinstance(raw.get("expected_variables"), dict)
            else {}
        ),
        "expected_tools": [str(t)[:80] for t in raw.get("expected_tools") or [] if t][
            :8
        ],
        "tool_hints": str(raw.get("tool_hints") or "")[:500],
        "variant_of": None,
        "enabled": True,
    }


async def generate(organization_id: int, campaign_id: str) -> None:
    """Background: write the campaign's scenarios, batch by batch."""
    from api.brand.analysis import resolve_analysis_model
    from api.brand.llm import chat_json

    campaign = await get(organization_id, campaign_id)
    if campaign is None:
        return
    try:
        model = await resolve_analysis_model(organization_id)
        if not model:
            raise CampaignError("no analysis model configured (Models › Analysis)")
        workflow = await db_client.get_workflow(
            campaign["workflow_id"], organization_id=organization_id
        )
        if workflow is None:
            raise CampaignError("agent not found")
        definition = await db_client.get_draft_version(workflow.id) or (
            await brand_db.get_workflow_version(
                workflow.id, workflow.released_definition_id
            )
        )
        brief = agent_brief(
            definition.workflow_json or {}, definition.workflow_configurations or {}
        )
        brief["tools"] = await _tool_names(organization_id, brief.pop("tool_uuids"))
        settings = await get_settings(organization_id)
        missing = campaign["count"] - len(campaign["scenarios"])
        seed = campaign["seed"] + len(campaign["scenarios"])
        levels = draw_levels(campaign["ranges"], missing, seed)
        speeds = draw_speeds(campaign["speed"], missing, seed)
        slots = [{"levels": lv, "speed": sp} for lv, sp in zip(levels, speeds)]
        _assign_pools(slots, settings, seed)
        campaign["generation"] = {
            "done": len(campaign["scenarios"]),
            "total": campaign["count"],
            "error": None,
        }
        for start in range(0, len(slots), GENERATION_BATCH):
            batch = slots[start : start + GENERATION_BATCH]
            payload = {
                "today": datetime.now(UTC).strftime("%A %d %B %Y"),
                "agent": {"name": workflow.name, **brief},
                "instructions": campaign.get("instructions"),
                "already_written": [
                    f"{s['title']} ({s['intent']})" for s in campaign["scenarios"]
                ][-60:],
                "slots": [
                    {
                        "slot": i + 1,
                        "levels": s["levels"],
                        "voice_gender": (s.get("voice") or {}).get("gender", "unknown"),
                    }
                    for i, s in enumerate(batch)
                ],
            }
            result = await chat_json(
                model,
                GENERATE_PROMPT.replace("{language}", campaign["language"]),
                payload,
                max_tokens=8000,
                temperature=0.7,
                timeout=240.0,
            )
            by_slot = {
                int(r.get("slot", 0)): r
                for r in result.get("scenarios") or []
                if isinstance(r, dict)
            }
            for i, slot in enumerate(batch):
                raw = by_slot.get(i + 1)
                if raw:
                    campaign["scenarios"].append(_scenario_from(raw, slot))
            campaign["generation"]["done"] = len(campaign["scenarios"])
            await save(organization_id, campaign)
        campaign["status"] = "ready"
        if len(campaign["scenarios"]) < campaign["count"]:
            campaign["generation"]["error"] = (
                f"the model wrote {len(campaign['scenarios'])} scenarios out of "
                f"{campaign['count']}"
            )
    except Exception as e:
        logger.warning(f"Test campaign {campaign_id}: generation failed: {e}")
        campaign["status"] = "ready" if campaign["scenarios"] else "failed"
        campaign["generation"] = {**(campaign.get("generation") or {}), "error": str(e)}
    await save(organization_id, campaign)


# --- Editing ----------------------------------------------------------------------

EDITABLE = (
    "title",
    "intent",
    "persona",
    "goal",
    "behaviour",
    "facts",
    "criteria",
    "forbidden",
    "expected_end_node",
    "expected_variables",
    "expected_tools",
    "tool_hints",
    "levels",
    "speed",
    "voice",
    "caller_number",
    "enabled",
)


def update_scenario(campaign: dict, scenario_id: str, changes: dict) -> dict:
    scenario = next((s for s in campaign["scenarios"] if s["id"] == scenario_id), None)
    if scenario is None:
        raise LookupError("scenario not found")
    for key in EDITABLE:
        if key not in changes:
            continue
        value = changes[key]
        if key == "levels":
            value = {
                k: max(1, min(5, int(v)))
                for k, v in (value or {}).items()
                if k in DIMENSIONS
            }
        elif key == "speed":
            value = round(max(SPEED_LIMITS[0], min(SPEED_LIMITS[1], float(value))), 2)
        elif key in ("criteria", "forbidden", "expected_tools"):
            value = [str(v) for v in value or [] if str(v).strip()]
        elif key in ("facts", "expected_variables"):
            value = {str(k): str(v) for k, v in (value or {}).items() if str(k).strip()}
        elif key == "voice" and value is not None:
            value = (_clean_voices([value]) or [None])[0]
        elif key == "enabled":
            value = bool(value)
        scenario[key] = value
    scenario["edited_at"] = _now()
    return scenario


def duplicate_scenario(campaign: dict, scenario_id: str, levels: dict | None) -> dict:
    """A variant: same request, other caller levels (edited afterwards)."""
    import copy

    source = next((s for s in campaign["scenarios"] if s["id"] == scenario_id), None)
    if source is None:
        raise LookupError("scenario not found")
    if len(campaign["scenarios"]) >= MAX_SCENARIOS:
        raise CampaignError(f"a campaign holds at most {MAX_SCENARIOS} scenarios")
    variant = copy.deepcopy(source)
    variant.update(
        id=uuid.uuid4().hex[:10],
        variant_of=source.get("variant_of") or source["id"],
        title=f"{source['title']} (variant)",
        edited_at=_now(),
    )
    if levels:
        update_scenario({"scenarios": [variant]}, variant["id"], {"levels": levels})
    campaign["scenarios"].insert(campaign["scenarios"].index(source) + 1, variant)
    return variant
