"use client";

import { Loader2, MessageSquareQuote, Play, Sparkles, Square } from "lucide-react";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { toast } from "sonner";

import { client } from "@/client/client.gen";
import { getWorkflowOptionsApiV1OrganizationsReportsWorkflowsGet } from "@/client/sdk.gen";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { detailFromError } from "@/lib/apiError";
import { useAuth } from "@/lib/auth";

// Recordings screen: recordings generated by the organization's voice model
// (api/brand/recordings.py), and an agent's greeting played from a recording.
// The greeting change is saved in a draft of the agent.

const MAX_CHARS = 1000;
const PREVIEW_CHARS = 300;
const NO_AGENT = "none";
const TESTER_NAME = "OxeePhone test caller";

interface Agent {
  id: number;
  name: string;
}

interface AgentGreeting {
  text: string;
  greeting_type: string;
  greeting_recording_id: string | null;
  voice: string | null;
  speed: number | null;
}

interface GreetingResult {
  workflow_id: number;
  draft_version_number: number;
}

function useAgents(enabled: boolean) {
  const auth = useAuth();
  const [agents, setAgents] = useState<Agent[]>([]);
  useEffect(() => {
    if (!enabled || auth.loading || !auth.isAuthenticated) return;
    void getWorkflowOptionsApiV1OrganizationsReportsWorkflowsGet().then((r) =>
      setAgents(((r.data as Agent[]) ?? []).filter((a) => a.name !== TESTER_NAME)),
    );
  }, [enabled, auth.loading, auth.isAuthenticated]);
  return agents;
}

async function loadGreeting(workflowId: number): Promise<AgentGreeting | null> {
  const response = await client.get<{ 200: AgentGreeting }, unknown>({
    url: `/api/v1/oxee/recordings/agent-greeting/${workflowId}`,
  });
  return (response.data as AgentGreeting) ?? null;
}

function draftToast(result: GreetingResult, what: string) {
  toast.success(`${what} — saved in draft v${result.draft_version_number}`, {
    description: "Publish the draft from the agent's editor to use it on calls.",
    action: { label: "Open agent", onClick: () => window.open(`/workflow/${result.workflow_id}`, "_self") },
  });
}

function AgentSelect({ agents, value, onChange, none }: { agents: Agent[]; value: string; onChange: (v: string) => void; none?: string }) {
  return (
    <Select value={value} onValueChange={onChange}>
      <SelectTrigger><SelectValue placeholder="Choose an agent" /></SelectTrigger>
      <SelectContent>
        {none && <SelectItem value={NO_AGENT}>{none}</SelectItem>}
        {agents.map((a) => (
          <SelectItem key={a.id} value={String(a.id)}>{a.name}</SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
}

function Listen({ voice, speed, text }: { voice: string; speed: number | null; text: string }) {
  const [state, setState] = useState<"idle" | "loading" | "playing">("idle");
  const audio = useRef<HTMLAudioElement | null>(null);
  const stop = () => {
    audio.current?.pause();
    audio.current = null;
    setState("idle");
  };
  useEffect(() => stop, []);
  return (
    <Button
      type="button"
      variant="outline"
      size="sm"
      className="gap-1.5"
      disabled={state === "loading"}
      onClick={async () => {
        if (state === "playing") return stop();
        setState("loading");
        const response = await client.post<{ 200: Blob }, unknown>({
          url: "/api/v1/oxee/recordings/preview",
          body: { voice: voice.trim() || null, speed, text: text.trim().slice(0, PREVIEW_CHARS) || null },
          headers: { "Content-Type": "application/json" },
          parseAs: "blob",
        });
        if (response.error || !response.data) {
          setState("idle");
          toast.error(detailFromError(response.error, "This voice could not be played"));
          return;
        }
        const url = URL.createObjectURL(response.data as Blob);
        const el = new Audio(url);
        audio.current = el;
        el.onended = () => {
          URL.revokeObjectURL(url);
          setState("idle");
        };
        setState("playing");
        void el.play();
      }}
    >
      {state === "loading" ? <Loader2 className="h-4 w-4 animate-spin" /> : state === "playing" ? <Square className="h-4 w-4" /> : <Play className="h-4 w-4" />}
      Listen
    </Button>
  );
}

export function GenerateRecordingDialog({
  open,
  onOpenChange,
  onCreated,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onCreated: () => void;
}) {
  const agents = useAgents(open);
  const [agent, setAgent] = useState(NO_AGENT);
  const [useAsGreeting, setUseAsGreeting] = useState(true);
  const [text, setText] = useState("");
  const [voice, setVoice] = useState("");
  const [speed, setSpeed] = useState<number | null>(null);
  const [name, setName] = useState("");
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    if (open) return;
    setAgent(NO_AGENT);
    setUseAsGreeting(true);
    setText("");
    setVoice("");
    setSpeed(null);
    setName("");
  }, [open]);

  const pickAgent = async (value: string) => {
    setAgent(value);
    if (value === NO_AGENT) return;
    const greeting = await loadGreeting(Number(value));
    if (!greeting) return;
    // Prefill what is still empty with the agent's greeting and voice.
    setText((t) => t || greeting.text);
    setVoice((v) => v || greeting.voice || "");
    setSpeed((s) => s ?? greeting.speed ?? null);
  };

  const hasVariables = /\{\{.*?\}\}/.test(text);
  const agentName = agents.find((a) => String(a.id) === agent)?.name;

  const submit = async () => {
    setBusy(true);
    const response = await client.post<{ 200: { recording_id: string; greeting: GreetingResult | null } }, unknown>({
      url: "/api/v1/oxee/recordings/generate",
      body: {
        text,
        voice: voice.trim() || null,
        speed,
        name: name.trim() || null,
        greeting_workflow_id: agent !== NO_AGENT && useAsGreeting ? Number(agent) : null,
      },
      headers: { "Content-Type": "application/json" },
    });
    setBusy(false);
    if (response.error) {
      toast.error(detailFromError(response.error, "The recording could not be generated"));
      return;
    }
    const data = response.data as { recording_id: string; greeting: GreetingResult | null };
    if (data.greeting) draftToast(data.greeting, `Recording ${data.recording_id} is the greeting of ${agentName}`);
    else toast.success(`Recording ${data.recording_id} generated`);
    onCreated();
    onOpenChange(false);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-xl">
        <DialogHeader>
          <DialogTitle>Generate a recording</DialogTitle>
          <DialogDescription>
            The text is spoken by the organization&apos;s voice model with the voice and speed below, then stored as a
            recording. A recorded greeting starts playing at once, without waiting for the voice model.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          <div className="space-y-1.5">
            <Label className="text-xs">Agent (optional)</Label>
            <AgentSelect agents={agents} value={agent} onChange={(v) => void pickAgent(v)} none="No agent" />
            {agent !== NO_AGENT && (
              <label className="flex items-center gap-2 pt-1 text-xs">
                <Checkbox checked={useAsGreeting} onCheckedChange={(v) => setUseAsGreeting(v === true)} />
                Use it as this agent&apos;s greeting (in a draft; the text greeting is kept and can be switched back)
              </label>
            )}
          </div>

          <div className="space-y-1.5">
            <div className="flex items-center">
              <Label htmlFor="rec_text" className="text-xs">Text</Label>
              <span className="ml-auto text-[11px] tabular-nums text-muted-foreground">{text.length} / {MAX_CHARS}</span>
            </div>
            <Textarea id="rec_text" rows={4} maxLength={MAX_CHARS} value={text} onChange={(e) => setText(e.target.value)} placeholder="Bonjour, vous êtes bien chez…" />
            {hasVariables && (
              <p className="text-xs text-amber-600 dark:text-amber-400">
                The text holds variables ({"{{…}}"}): a recording is fixed, they will be read as written.
              </p>
            )}
          </div>

          <div className="grid gap-4 sm:grid-cols-[minmax(0,1fr)_auto]">
            <div className="space-y-1.5">
              <Label htmlFor="rec_voice" className="text-xs">Voice id</Label>
              <Input id="rec_voice" value={voice} onChange={(e) => setVoice(e.target.value)} placeholder="Organization voice" className="font-mono text-xs" />
            </div>
            <div className="flex items-end">
              <Listen voice={voice} speed={speed} text={text} />
            </div>
          </div>

          <div className="space-y-1.5">
            <div className="flex items-center">
              <Label htmlFor="rec_speed" className="text-xs">Speed</Label>
              <button type="button" onClick={() => setSpeed(null)} className="ml-auto text-[11px] text-muted-foreground hover:text-foreground">
                {speed === null ? "organization" : "back to organization"}
              </button>
            </div>
            <div className="flex items-center gap-3">
              <input
                id="rec_speed"
                type="range"
                aria-label="Speed"
                min={0.5}
                max={2}
                step={0.05}
                value={speed ?? 1}
                onChange={(e) => setSpeed(Number(e.target.value))}
                className={`h-1.5 w-full cursor-pointer accent-[var(--cta)] ${speed === null ? "opacity-60" : ""}`}
              />
              <span className="w-12 text-right text-xs tabular-nums">{speed === null ? "—" : `${speed.toFixed(2)}×`}</span>
            </div>
          </div>

          <div className="space-y-1.5">
            <Label htmlFor="rec_name" className="text-xs">Name (optional)</Label>
            <Input id="rec_name" value={name} maxLength={64} onChange={(e) => setName(e.target.value)} placeholder="accueil_standard" className="font-mono text-xs" />
            <p className="text-[11px] text-muted-foreground">Letters, digits, - and _. Generated when empty.</p>
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button>
          <Button className="gap-1.5" disabled={busy || !text.trim()} onClick={() => void submit()}>
            {busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />} Generate
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

/** Row action: an agent's greeting from this recording, or back to text. */
export function UseAsGreetingButton({ recordingPk, recordingId }: { recordingPk: number; recordingId: string }) {
  const [open, setOpen] = useState(false);
  const agents = useAgents(open);
  const [agent, setAgent] = useState("");
  const [current, setCurrent] = useState<AgentGreeting | null>(null);
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    if (!agent) return setCurrent(null);
    void loadGreeting(Number(agent)).then(setCurrent);
  }, [agent]);

  const usesThis = current?.greeting_type === "audio" && current.greeting_recording_id === String(recordingPk);

  const save = async (pk: number | null) => {
    setBusy(true);
    const response = await client.post<{ 200: GreetingResult }, unknown>({
      url: "/api/v1/oxee/recordings/greeting",
      body: { workflow_id: Number(agent), recording_pk: pk },
      headers: { "Content-Type": "application/json" },
    });
    setBusy(false);
    if (response.error) {
      toast.error(detailFromError(response.error, "The greeting could not be changed"));
      return;
    }
    const name = agents.find((a) => String(a.id) === agent)?.name ?? "the agent";
    draftToast(response.data as GreetingResult, pk ? `${recordingId} is the greeting of ${name}` : `${name} speaks its text greeting again`);
    setOpen(false);
  };

  return (
    <>
      <Button variant="ghost" size="sm" title="Use as an agent's greeting" onClick={() => setOpen(true)}>
        <MessageSquareQuote className="h-4 w-4" />
      </Button>
      <Dialog open={open} onOpenChange={(o) => { setOpen(o); if (!o) setAgent(""); }}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Greeting from {recordingId}</DialogTitle>
            <DialogDescription>
              The agent plays this recording instead of speaking its greeting text. The change is saved in a draft; the
              text stays in the agent and can be switched back here or in the start node.
            </DialogDescription>
          </DialogHeader>
          <AgentSelect agents={agents} value={agent} onChange={setAgent} />
          {current && (
            <p className="text-xs text-muted-foreground">
              Current greeting:{" "}
              {current.greeting_type === "audio"
                ? usesThis ? "this recording." : "another recording."
                : current.text ? <>text “{current.text.slice(0, 120)}{current.text.length > 120 ? "…" : ""}”</> : "none (generated)."}{" "}
              <Link href={`/workflow/${agent}`} className="underline underline-offset-2">Open agent</Link>
            </p>
          )}
          <DialogFooter className="gap-2">
            {current?.greeting_type === "audio" && (
              <Button variant="outline" disabled={busy} onClick={() => void save(null)}>Back to the text greeting</Button>
            )}
            <Button disabled={busy || !agent || usesThis} onClick={() => void save(recordingPk)}>
              {busy && <Loader2 className="mr-1.5 h-4 w-4 animate-spin" />} Use as greeting
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}
